### ISSUE TITLE
Softlayer Storage request fails for esxi host name with - e.g. dal13-pod2-6tb-host002

### ISSUE THREAD

**Issue by sunilagrawal86** [IBM-Cloud/terraform-provider-ibm#2056]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
bash-4.4$ terraform -v
Terraform v0.11.11

### Affected Resource(s)
Please list the resources as a list, for example:
data : ibm_compute_bare_metal

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```
variable "hosts" {
  default = [
    "dal13-pod2-6tb-host001",
    "dal13-pod2-6tb-host002",
    "dal13-pod2-6tb-host003",
  ]
}


data "ibm_compute_bare_metal" "bare_metal"

{
	
	count         = "${length(var.hosts)}"
  	hostname      = "${var.hosts[count.index]}"
    domain = "imzcloud.ibmammsap.local"

}


```

### Debug Output
```

rror refreshing state: 1 error(s) occurred:* data.ibm_compute_bare_metal.bare_metal: 2 error(s) occurred:
* data.ibm_compute_bare_metal.bare_metal[0]: data.ibm_compute_bare_metal.bare_metal.0: unexpected EOF
* data.ibm_compute_bare_metal.bare_metal[1]: data.ibm_compute_bare_metal.bare_metal.1: unexpected EOF


panic: runtime error: invalid memory address or nil pointer dereference
2020-11-20T15:26:23.970Z [DEBUG] plugin.terraform-provider-ibm_v1.10.0: [signal SIGSEGV: segmentation violation code=0x1 addr=0xa8 pc=0x18b7c0c]
2020-11-20T15:26:23.970Z [DEBUG] plugin.terraform-provider-ibm_v1.10.0: 
2020-11-20T15:26:23.970Z [DEBUG] plugin.terraform-provider-ibm_v1.10.0: goroutine 104 [running]:
2020-11-20T15:26:23.970Z [DEBUG] plugin.terraform-provider-ibm_v1.10.0: github.com/IBM-Cloud/terraform-provider-ibm/ibm.dataSourceIBMComputeBareMetalRead(0xc0008d2c40, 0x2287280, 0xc0003a8d80, 0xc0008d2c40, 0x0)
2020-11-20T15:26:23.970Z [DEBUG] plugin.terraform-provider-ibm_v1.10.0: 	/root/go/src/github.com/IBM-Cloud/terraform-provider-ibm/ibm/data_source_ibm_compute_bare_metal.go:317 +0x82c
2020-11-20T15:26:23.970Z [DEBUG] plugin.terraform-provider-ibm_v1.10.0: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).ReadDataApply(0xc000aa5c80, 0xc000c9e6c0, 0x2287280, 0xc0003a8d80, 0xc000bac498, 0x40dc01, 0xc000cb6660)
2020-11-20T15:26:23.970Z [DEBUG] plugin.terraform-provider-ibm_v1.10.0: 	/root/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.6.0/helper/schema/resource.go:398 +0x88
2020-11-20T15:26:23.970Z [DEBUG] plugin.terraform-provider-ibm_v1.10.0: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).ReadDataApply(0xc000c61500, 0xc000cbb2c0, 0xc000c9e6c0, 0xc000cb6660, 0xc000cd4450, 0x18)
2020-11-20T15:26:23.970Z [DEBUG] plugin.terraform-provider-ibm_v1.10.0: 	/root/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.6.0/helper/schema/provider.go:451 +0x8f
2020-11-20T15:26:23.970Z [DEBUG] plugin.terraform-provider-ibm_v1.10.0: github.com/hashicorp/terraform-plugin-sdk/plugin.(*ResourceProviderServer).ReadDataApply(0xc000917fc0, 0xc00057fa60, 0xc00057fa90, 0x0, 0x0)
2020-11-20T15:26:23.970Z [DEBUG] plugin.terraform-provider-ibm_v1.10.0: 	/root/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.6.0/plugin/resource_provider.go:607 +0x4e
2020-11-20T15:26:23.970Z [DEBUG] plugin.terraform-provider-ibm_v1.10.0: reflect.Value.call(0xc0000ab1a0, 0xc000412208, 0x13, 0x22a0277, 0x4, 0xc0008f0f18, 0x3, 0x3, 0x0, 0x0, ...)
2020-11-20T15:26:23.970Z [DEBUG] plugin.terraform-provider-ibm_v1.10.0: 	/usr/local/go/src/reflect/value.go:460 +0x5f6
2020-11-20T15:26:23.970Z [DEBUG] plugin.terraform-provider-ibm_v1.10.0: reflect.Value.Call(0xc0000ab1a0, 0xc000412208, 0x13, 0xc00048a718, 0x3, 0x3, 0x0, 0x0, 0x0)
2020-11-20T15:26:23.970Z [DEBUG] plugin.terraform-provider-ibm_v1.10.0: 	/usr/local/go/src/reflect/value.go:321 +0xb4
2020-11-20T15:26:23.970Z [DEBUG] plugin.terraform-provider-ibm_v1.10.0: net/rpc.(*service).call(0xc0003eec00, 0xc00086a7d0, 0xc000837db0, 0xc000837dc0, 0xc000c86380, 0xc000c9e040, 0x1da68e0, 0xc00057fa60, 0x16, 0x1da6920, ...)
2020-11-20T15:26:23.970Z [DEBUG] plugin.terraform-provider-ibm_v1.10.0: 	/usr/local/go/src/net/rpc/server.go:377 +0x16f
2020-11-20T15:26:23.970Z [DEBUG] plugin.terraform-provider-ibm_v1.10.0: created by net/rpc.(*Server).ServeCodec
2020-11-20T15:26:23.970Z [DEBUG] plugin.terraform-provider-ibm_v1.10.0: 	/usr/local/go/src/net/rpc/server.go:474 +0x42b
2020/11/20 15:26:23 [ERROR] root: eval: *terraform.EvalReadDataApply, err: data.ibm_compute_bare_metal.bare_metal.0: unexpected EOF
2020/11/20 15:26:23 [ERROR] root: eval: *terraform.EvalSequence, err: data.ibm_compute_bare_metal.bare_metal.0: unexpected EOF
2020/11/20 15:26:23 [TRACE] [walkRefresh] Exiting eval tree: data.ibm_compute_bare_metal.bare_metal[0]
2020-11-20T15:26:23.974Z [DEBUG] plugin: plugin process exited: path=/home/terraform/stacks/stackjobs/temp_bc9a2040-2b44-11eb-8557-3184d43eea93/.terraform.d/plugins/terraform-provider-ibm_v1.10.0
2020/11/20 15:26:23 [ERROR] root: eval: *terraform.EvalReadDataApply, err: data.ibm_compute_bare_metal.bare_metal.1: unexpected EOF
2020/11/20 15:26:23 [ERROR] root: eval: *terraform.EvalSequence, err: data.ibm_compute_bare_metal.bare_metal.1: unexpected EOF
2020/11/20 15:26:23 [TRACE] [walkRefresh] Exiting eval tree: data.ibm_compute_bare_metal.bare_metal[1]
2020/11/20 15:26:23 [TRACE] dag/walk: upstream errored, not walking "root"
2020/11/20 15:26:23 [TRACE] dag/walk: upstream errored, not walking "provider.ibm (close)"
2020/11/20 15:26:23 [TRACE] dag/walk: upstream errored, not walking "root"
2020/11/20 15:26:23 [DEBUG] plugin: waiting for all plugin processes to complete...
2020-11-20T15:26:23.982Z [WARN ] plugin: error closing client during Kill: err="connection is shut down"
```

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
It should be able to list all the ids without any issue 

### Actual Behavior
Terraform crashes 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by hkantare** [comment]
closing the issue due to no activity from long time. Please feel free to open a new issue if the issue still exists
