### ISSUE TITLE
github.com/IBM-Cloud/terraform-provider-ibm/ibm.expireRuleGet -> panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mschenk42** [IBM-Cloud/terraform-provider-ibm#2151]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.12.29
+ provider.ibm v1.19.0
+ provider.null v2.1.2

### Affected Resource(s)
- ibm_cos_bucket

```
 panic: runtime error: invalid memory address or nil pointer dereference
 [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2b4c2ff]
 
 goroutine 223 [running]:
 github.com/IBM-Cloud/terraform-provider-ibm/ibm.expireRuleGet(0xc0002d8200, 0x1, 0x1, 0xc0006af900, 0x0, 0x1)
 	/Users/harinireddy/go/src/github.com/IBM-Cloud/terraform-provider-ibm/ibm/structures.go:725 +0x19f
 github.com/IBM-Cloud/terraform-provider-ibm/ibm.resourceIBMCOSRead(0xc0001a7570, 0x3213480, 0xc000289100, 0xc0001a7570, 0x0)
 	/Users/harinireddy/go/src/github.com/IBM-Cloud/terraform-provider-ibm/ibm/resource_ibm_cos_bucket.go:666 +0x112c
 github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000993d80, 0xc000831400, 0x3213480, 0xc000289100, 0xc0004870f0, 0x0, 0x0)
 	/Users/harinireddy/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.6.0/helper/schema/resource.go:455 +0x129
 github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00000e928, 0x36362a0, 0xc00067d9e0, 0xc000831310, 0xc00000e928, 0xc00067d9e0, 0xc0010d7b78)
 	/Users/harinireddy/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.6.0/internal/helper/plugin/grpc_provider.go:525 +0x3dd
 github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x31738c0, 0xc00000e928, 0x36362a0, 0xc00067d9e0, 0xc000b98de0, 0x0, 0x36362a0, 0xc00067d9e0, 0xc00100a000, 0x3fd)
 	/Users/harinireddy/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.6.0/internal/tfplugin5/tfplugin5.pb.go:3153 +0x214
 google.golang.org/grpc.(*Server).processUnaryRPC(0xc000602a80, 0x364cf80, 0xc0004d1380, 0xc000494e00, 0xc0003b8540, 0x43ae190, 0x0, 0x0, 0x0)
 	/Users/harinireddy/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:1024 +0x522
 google.golang.org/grpc.(*Server).handleStream(0xc000602a80, 0x364cf80, 0xc0004d1380, 0xc000494e00, 0x0)
 	/Users/harinireddy/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:1313 +0xd34
 google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0004e24f0, 0xc000602a80, 0x364cf80, 0xc0004d1380, 0xc000494e00)
 	/Users/harinireddy/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:722 +0xa5
 created by google.golang.org/grpc.(*Server).serveStreams.func1
 	/Users/harinireddy/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:720 +0xa5

```

**Comment by hkantare** [comment]
Released in https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.20.0
Cloud docs will be updated soon
Registry docs:
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs

**Comment by hkantare** [comment]
closing the issue
