### ISSUE TITLE
terraform crash - ibm_resource_key 

### ISSUE THREAD

**Issue by powellquiring** [IBM-Cloud/terraform-provider-ibm#2462]
Terraform apply a the configuration using ibm provider version 1.21.2 which works ok.  1.23 causes panic.

Notice the panic has /Users/harinireddy/go/src/github.com/.... someone's home directory, is that right?

```
➜  bug-resourece-key git:(master) ✗ tf version
Terraform v0.14.9
+ provider registry.terraform.io/ibm-cloud/ibm v1.21.2
```

Taint the resource and build again with this version, 1.23 or 1.22
```
➜  bug-resourece-key git:(master) ✗ tf version
Terraform v0.14.9
+ provider registry.terraform.io/ibm-cloud/ibm v1.23.0
```

Results in:

```
ibm_resource_key.resource_key: Creating...
ibm_resource_key.resource_key: Creation complete after 3s [id=crn:v1:bluemix:public:databases-for-redis:us-south:a/713c783d9a507a53135fe6793c37cc74:c6f9ee3d-f1a3-4819-b541-d9e8f58708d1:resource-key:6cc087e8-9d4c-4bc1-8a45-da7b0581a466]

Apply complete! Resources: 5 added, 0 changed, 0 destroyed.
➜  bug-resourece-key git:(master) ✗ tf init -upgrade

Initializing the backend...

Initializing provider plugins...
- Finding ibm-cloud/ibm versions matching "1.23.0"...
- Using ibm-cloud/ibm v1.23.0 from the shared cache directory

Terraform has made some changes to the provider dependency selections recorded
in the .terraform.lock.hcl file. Review those changes and commit them to your
version control system if they represent changes you intended to make.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
➜  bug-resourece-key git:(master) ✗ tf taint ibm_resource_key.resource_key
Resource instance ibm_resource_key.resource_key has been marked as tainted.
➜  bug-resourece-key git:(master) ✗ tfa
ibm_is_vpc.main: Refreshing state... [id=r006-6eb9ac65-648c-49c5-9eb3-0828d428299c]
ibm_database.redis: Refreshing state... [id=crn:v1:bluemix:public:databases-for-redis:us-south:a/713c783d9a507a53135fe6793c37cc74:c6f9ee3d-f1a3-4819-b541-d9e8f58708d1::]
ibm_is_vpc_address_prefix.main: Refreshing state... [id=r006-6eb9ac65-648c-49c5-9eb3-0828d428299c/r006-3640ddff-736b-4fb9-bd6a-f0a2e12f4c0e]
ibm_resource_key.resource_key: Refreshing state... [id=crn:v1:bluemix:public:databases-for-redis:us-south:a/713c783d9a507a53135fe6793c37cc74:c6f9ee3d-f1a3-4819-b541-d9e8f58708d1:resource-key:6cc087e8-9d4c-4bc1-8a45-da7b0581a466]

Warning: Deprecated Attribute

The generation field is deprecated and will be removed after couple of
releases


Error: rpc error: code = Unavailable desc = transport is closing



Error: rpc error: code = Unavailable desc = transport is closing


panic: Unknown: %!!(MISSING)s(float64=0)
2021-04-05T06:14:14.188-0700 [DEBUG] plugin.terraform-provider-ibm_v1.23.0:
2021-04-05T06:14:14.188-0700 [DEBUG] plugin.terraform-provider-ibm_v1.23.0: goroutine 273 [running]:
2021-04-05T06:14:14.188-0700 [DEBUG] plugin.terraform-provider-ibm_v1.23.0: github.com/IBM-Cloud/terraform-provider-ibm/ibm.flatten(0xc00041f320, 0xc00104ec40, 0x1a, 0x3220ea0, 0xc000ccd590, 0x94)
2021-04-05T06:14:14.188-0700 [DEBUG] plugin.terraform-provider-ibm_v1.23.0: 	/Users/harinireddy/go/src/github.com/IBM-Cloud/terraform-provider-ibm/ibm/flatten.go:52 +0x465
2021-04-05T06:14:14.188-0700 [DEBUG] plugin.terraform-provider-ibm_v1.23.0: github.com/IBM-Cloud/terraform-provider-ibm/ibm.flattenMap(0xc00041f320, 0xc00104ec00, 0x11, 0x3295800, 0xc00041f200, 0x15)
2021-04-05T06:14:14.188-0700 [DEBUG] plugin.terraform-provider-ibm_v1.23.0: 	/Users/harinireddy/go/src/github.com/IBM-Cloud/terraform-provider-ibm/ibm/flatten.go:66 +0x285
2021-04-05T06:14:14.188-0700 [DEBUG] plugin.terraform-provider-ibm_v1.23.0: github.com/IBM-Cloud/terraform-provider-ibm/ibm.flatten(0xc00041f320, 0xc00104ec00, 0x11, 0x3220ea0, 0xc000ccd3c0, 0x94)
2021-04-05T06:14:14.188-0700 [DEBUG] plugin.terraform-provider-ibm_v1.23.0: 	/Users/harinireddy/go/src/github.com/IBM-Cloud/terraform-provider-ibm/ibm/flatten.go:46 +0x374
2021-04-05T06:14:14.188-0700 [DEBUG] plugin.terraform-provider-ibm_v1.23.0: github.com/IBM-Cloud/terraform-provider-ibm/ibm.flattenMap(0xc00041f320, 0xc000c9ea04, 0xa, 0x3295800, 0xc00041f140, 0x15)
2021-04-05T06:14:14.188-0700 [DEBUG] plugin.terraform-provider-ibm_v1.23.0: 	/Users/harinireddy/go/src/github.com/IBM-Cloud/terraform-provider-ibm/ibm/flatten.go:66 +0x285
2021-04-05T06:14:14.188-0700 [DEBUG] plugin.terraform-provider-ibm_v1.23.0: github.com/IBM-Cloud/terraform-provider-ibm/ibm.flatten(0xc00041f320, 0xc000c9ea04, 0xa, 0x3295800, 0xc00041f140, 0x15)
2021-04-05T06:14:14.188-0700 [DEBUG] plugin.terraform-provider-ibm_v1.23.0: 	/Users/harinireddy/go/src/github.com/IBM-Cloud/terraform-provider-ibm/ibm/flatten.go:46 +0x374
2021-04-05T06:14:14.188-0700 [DEBUG] plugin.terraform-provider-ibm_v1.23.0: github.com/IBM-Cloud/terraform-provider-ibm/ibm.Flatten(0xc00041f110, 0x12e8)
2021-04-05T06:14:14.188-0700 [DEBUG] plugin.terraform-provider-ibm_v1.23.0: 	/Users/harinireddy/go/src/github.com/IBM-Cloud/terraform-provider-ibm/ibm/flatten.go:24 +0x150
2021-04-05T06:14:14.188-0700 [DEBUG] plugin.terraform-provider-ibm_v1.23.0: github.com/IBM-Cloud/terraform-provider-ibm/ibm.resourceIBMResourceKeyRead(0xc00012a300, 0x369aaa0, 0xc000f5a000, 0x4a8ae70, 0x3791948)
2021-04-05T06:14:14.188-0700 [DEBUG] plugin.terraform-provider-ibm_v1.23.0: 	/Users/harinireddy/go/src/github.com/IBM-Cloud/terraform-provider-ibm/ibm/resource_ibm_resource_key.go:283 +0x2d9
2021-04-05T06:14:14.188-0700 [DEBUG] plugin.terraform-provider-ibm_v1.23.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000a12600, 0x3b40de0, 0xc000494100, 0xc00012a300, 0x369aaa0, 0xc000f5a000, 0x0, 0x0, 0x0)
2021-04-05T06:14:14.188-0700 [DEBUG] plugin.terraform-provider-ibm_v1.23.0: 	/Users/harinireddy/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.4/helper/schema/resource.go:290 +0x88
2021-04-05T06:14:14.188-0700 [DEBUG] plugin.terraform-provider-ibm_v1.23.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000a12600, 0x3b40de0, 0xc000494100, 0xc0003ee070, 0x369aaa0, 0xc000f5a000, 0xc000486fb0, 0x0, 0x0, 0x0)
2021-04-05T06:14:14.188-0700 [DEBUG] plugin.terraform-provider-ibm_v1.23.0: 	/Users/harinireddy/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.4/helper/schema/resource.go:564 +0x1cb
2021-04-05T06:14:14.188-0700 [DEBUG] plugin.terraform-provider-ibm_v1.23.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000117140, 0x3b40de0, 0xc000494100, 0xc000494140, 0xc000494100, 0x3505ac0, 0x35c1500)
2021-04-05T06:14:14.188-0700 [DEBUG] plugin.terraform-provider-ibm_v1.23.0: 	/Users/harinireddy/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.4/helper/schema/grpc_provider.go:575 +0x43b
2021-04-05T06:14:14.188-0700 [DEBUG] plugin.terraform-provider-ibm_v1.23.0: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc0002794e0, 0x3b40de0, 0xc000494100, 0xc0004d0300, 0xc0002794e0, 0xc000cb49f0, 0xc0010a1ba0)
2021-04-05T06:14:14.188-0700 [DEBUG] plugin.terraform-provider-ibm_v1.23.0: 	/Users/harinireddy/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:298 +0x105
2021-04-05T06:14:14.188-0700 [DEBUG] plugin.terraform-provider-ibm_v1.23.0: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x35c1500, 0xc0002794e0, 0x3b40ea0, 0xc000cb49f0, 0xc0004d02a0, 0x0, 0x3b40ea0, 0xc000cb49f0, 0xc000dae600, 0x1849)
2021-04-05T06:14:14.188-0700 [DEBUG] plugin.terraform-provider-ibm_v1.23.0: 	/Users/harinireddy/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
2021-04-05T06:14:14.188-0700 [DEBUG] plugin.terraform-provider-ibm_v1.23.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000a90380, 0x3b5d100, 0xc000102f00, 0xc000498b00, 0xc000a51230, 0x4a2b6f0, 0x0, 0x0, 0x0)
2021-04-05T06:14:14.188-0700 [DEBUG] plugin.terraform-provider-ibm_v1.23.0: 	/Users/harinireddy/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x522
2021-04-05T06:14:14.188-0700 [DEBUG] plugin.terraform-provider-ibm_v1.23.0: google.golang.org/grpc.(*Server).handleStream(0xc000a90380, 0x3b5d100, 0xc000102f00, 0xc000498b00, 0x0)
2021-04-05T06:14:14.188-0700 [DEBUG] plugin.terraform-provider-ibm_v1.23.0: 	/Users/harinireddy/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd05
2021-04-05T06:14:14.188-0700 [DEBUG] plugin.terraform-provider-ibm_v1.23.0: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00048c930, 0xc000a90380, 0x3b5d100, 0xc000102f00, 0xc000498b00)
2021-04-05T06:14:14.188-0700 [DEBUG] plugin.terraform-provider-ibm_v1.23.0: 	/Users/harinireddy/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xa5
2021-04-05T06:14:14.188-0700 [DEBUG] plugin.terraform-provider-ibm_v1.23.0: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-04-05T06:14:14.188-0700 [DEBUG] plugin.terraform-provider-ibm_v1.23.0: 	/Users/harinireddy/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
2021/04/05 06:14:14 [TRACE] vertex "ibm_resource_key.resource_key": visit complete
2021/04/05 06:14:14 [TRACE] vertex "ibm_resource_key.resource_key": dynamic subgraph encountered errors
2021/04/05 06:14:14 [TRACE] vertex "ibm_resource_key.resource_key": visit complete
2021-04-05T06:14:14.191-0700 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021/04/05 06:14:14 [TRACE] vertex "ibm_resource_key.resource_key (expand)": dynamic subgraph encountered errors
2021/04/05 06:14:14 [TRACE] vertex "ibm_resource_key.resource_key (expand)": visit complete
2021/04/05 06:14:14 [TRACE] vertex "ibm_is_vpc_address_prefix.main": visit complete
2021/04/05 06:14:14 [TRACE] vertex "ibm_is_vpc_address_prefix.main": dynamic subgraph encountered errors
2021/04/05 06:14:14 [TRACE] vertex "ibm_is_vpc_address_prefix.main": visit complete
2021/04/05 06:14:14 [TRACE] vertex "ibm_is_vpc_address_prefix.main (expand)": dynamic subgraph encountered errors
2021/04/05 06:14:14 [TRACE] vertex "ibm_is_vpc_address_prefix.main (expand)": visit complete
2021/04/05 06:14:14 [TRACE] dag/walk: upstream of "ibm_is_subnet.main (expand)" errored, so skipping
2021/04/05 06:14:14 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/ibm-cloud/ibm\"] (close)" errored, so skipping
2021-04-05T06:14:14.191-0700 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/ibm-cloud/ibm/1.23.0/darwin_amd64/terraform-provider-ibm_v1.23.0 pid=84400 error="exit status 2"
2021/04/05 06:14:14 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2021/04/05 06:14:14 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021/04/05 06:14:14 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2021/04/05 06:14:14 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2021-04-05T06:14:14.192-0700 [DEBUG] plugin: plugin exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
➜  bug-resourece-key git:(master) ✗
tf
```

terraform config:
```
terraform {
  required_providers {
    ibm = {
      source  = "IBM-Cloud/ibm"
      #version = "= 1.21.2"
      version = "= 1.23.0"
    }
  }
  required_version = "= 0.14.9"
}

variable basename {}
variable ibmcloud_api_key {}
variable region {}
variable resource_group_name {}

provider "ibm" {
  ibmcloud_api_key = var.ibmcloud_api_key
  region           = var.region
  generation       = 2
}

data "ibm_resource_group" "group" {
  name = var.resource_group_name
}

locals {
  name = var.basename
  resource_group_id = data.ibm_resource_group.group.id
  cidr0 = "192.168.0.0/24"
  zone = "${var.region}-1"
}

resource "ibm_is_vpc" "main" {
  name                      = local.name
  resource_group            = local.resource_group_id
  address_prefix_management = "manual"
}

resource "ibm_is_vpc_address_prefix" "main" {
  name     = local.name
  zone     = local.zone
  vpc      = ibm_is_vpc.main.id
  cidr     = local.cidr0
}
resource "ibm_is_subnet" "main" {
  name     = local.name
  vpc            = ibm_is_vpc_address_prefix.main.vpc
  zone            = ibm_is_vpc_address_prefix.main.zone
  ipv4_cidr_block = ibm_is_vpc_address_prefix.main.cidr
  resource_group  = local.resource_group_id
}

resource "ibm_database" "redis" {
  name              = local.name
  resource_group_id = local.resource_group_id
  plan              = "standard"
  service           = "databases-for-redis"
  location          = var.region
  service_endpoints = "private"
}

resource "ibm_resource_key" "resource_key" {
  name                 = local.name
  resource_instance_id = ibm_database.redis.id
  role                 = "Administrator"
}


```

**Comment by powellquiring** [comment]
Created a cut down in the description above.

**Comment by hkantare** [comment]
This issue is fixed in latest minor release
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.23.1

**Comment by kavya498** [comment]
Closing this issue.. 
Thank you.
