### ISSUE TITLE
terraform crash when creating/importing LBaaS

### ISSUE THREAD

**Issue by jkwong888** [IBM-Cloud/terraform-provider-ibm#286]
terraform crashes when I create a LBaaS instance, potentially because of lack of health monitors.  this was working in 0.9.x, but not 0.10.0

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_lbaas

here is an example lbaas that i'm creating, but i'm getting crashes on all lbaas instances we create:

```
resource "ibm_lbaas" "master-lbaas-int" {
  count = "${var.master["nodes"] > 1 ? 1 : 0}"
  name = "${var.deployment}-${random_id.clusterid.hex}-internal"
  type = "PRIVATE"

  subnets = ["${ibm_compute_vm_instance.icp-master.0.private_subnet_id}"]
  protocols = [
    {
      frontend_protocol = "TCP"
      frontend_port = 8001

      backend_protocol = "TCP"
      backend_port = 8001
    },
    {
      frontend_protocol = "TCP"
      frontend_port = 9443

      backend_protocol = "TCP"
      backend_port = 9443
    }
  ]
}

```

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

```
panic: runtime error: invalid memory address or nil pointer dereference
2018-06-19T09:07:10.014-0400 [DEBUG] plugin.terraform-provider-ibm: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1b5d78b]
2018-06-19T09:07:10.014-0400 [DEBUG] plugin.terraform-provider-ibm: 
2018-06-19T09:07:10.014-0400 [DEBUG] plugin.terraform-provider-ibm: goroutine 857 [running]:
2018-06-19T09:07:10.014-0400 [DEBUG] plugin.terraform-provider-ibm: github.com/terraform-providers/terraform-provider-ibm/ibm.flattenHealthMonitors(0xc420419400, 0x2, 0x4, 0x1c56780, 0xc4204e5280, 0x0)
2018-06-19T09:07:10.014-0400 [DEBUG] plugin.terraform-provider-ibm: 	/Users/sakshi/Documents/AlchemyProject/go_workspace/src/github.com/terraform-providers/terraform-provider-ibm/ibm/structures.go:695 +0x47b
2018-06-19T09:07:10.014-0400 [DEBUG] plugin.terraform-provider-ibm: github.com/terraform-providers/terraform-provider-ibm/ibm.resourceIBMLbaasRead(0xc420312d90, 0x1e86ba0, 0xc42098a000, 0x1e7c6e0, 0xc4201c0300)
2018-06-19T09:07:10.014-0400 [DEBUG] plugin.terraform-provider-ibm: 	/Users/sakshi/Documents/AlchemyProject/go_workspace/src/github.com/terraform-providers/terraform-provider-ibm/ibm/resource_ibm_lbaas.go:317 +0x51e
2018-06-19T09:07:10.014-0400 [DEBUG] plugin.terraform-provider-ibm: github.com/terraform-providers/terraform-provider-ibm/ibm.resourceIBMLbaasCreate(0xc420312d90, 0x1e86ba0, 0xc42098a000, 0xc420312d90, 0x0)
2018-06-19T09:07:10.014-0400 [DEBUG] plugin.terraform-provider-ibm: 	/Users/sakshi/Documents/AlchemyProject/go_workspace/src/github.com/terraform-providers/terraform-provider-ibm/ibm/resource_ibm_lbaas.go:290 +0x64d
2018-06-19T09:07:10.014-0400 [DEBUG] plugin.terraform-provider-ibm: github.com/terraform-providers/terraform-provider-ibm/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc420360690, 0xc42084afa0, 0xc42032df00, 0x1e86ba0, 0xc42098a000, 0xc4202add01, 0xc420081b88, 0x10b60fc)
2018-06-19T09:07:10.014-0400 [DEBUG] plugin.terraform-provider-ibm: 	/Users/sakshi/Documents/AlchemyProject/go_workspace/src/github.com/terraform-providers/terraform-provider-ibm/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:227 +0x35a
2018-06-19T09:07:10.014-0400 [DEBUG] plugin.terraform-provider-ibm: github.com/terraform-providers/terraform-provider-ibm/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc4203615e0, 0xc42084af50, 0xc42084afa0, 0xc42032df00, 0xc4203615e0, 0xc420832f00, 0xc42065d620)
2018-06-19T09:07:10.014-0400 [DEBUG] plugin.terraform-provider-ibm: 	/Users/sakshi/Documents/AlchemyProject/go_workspace/src/github.com/terraform-providers/terraform-provider-ibm/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:283 +0xa4
2018-06-19T09:07:10.014-0400 [DEBUG] plugin.terraform-provider-ibm: github.com/terraform-providers/terraform-provider-ibm/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc42065d540, 0xc42032dea0, 0xc42093bb90, 0x0, 0x0)
2018-06-19T09:07:10.014-0400 [DEBUG] plugin.terraform-provider-ibm: 	/Users/sakshi/Documents/AlchemyProject/go_workspace/src/github.com/terraform-providers/terraform-provider-ibm/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:527 +0x57
2018-06-19T09:07:10.014-0400 [DEBUG] plugin.terraform-provider-ibm: reflect.Value.call(0xc4201905a0, 0xc4206bb370, 0x13, 0x1eacc62, 0x4, 0xc420081f18, 0x3, 0x3, 0xc420880240, 0x0, ...)
2018-06-19T09:07:10.014-0400 [DEBUG] plugin.terraform-provider-ibm: 	/usr/local/Cellar/go/1.10/libexec/src/reflect/value.go:447 +0x969
2018-06-19T09:07:10.014-0400 [DEBUG] plugin.terraform-provider-ibm: reflect.Value.Call(0xc4201905a0, 0xc4206bb370, 0x13, 0xc420012718, 0x3, 0x3, 0x0, 0x0, 0x0)
2018-06-19T09:07:10.014-0400 [DEBUG] plugin.terraform-provider-ibm: 	/usr/local/Cellar/go/1.10/libexec/src/reflect/value.go:308 +0xa4
2018-06-19T09:07:10.015-0400 [DEBUG] plugin.terraform-provider-ibm: net/rpc.(*service).call(0xc420585780, 0xc42084aaa0, 0xc4207f13b0, 0xc4207f13c0, 0xc4201bc300, 0xc420512de0, 0x1c11b40, 0xc42032dea0, 0x16, 0x1c11b80, ...)
2018-06-19T09:07:10.015-0400 [DEBUG] plugin.terraform-provider-ibm: 	/usr/local/Cellar/go/1.10/libexec/src/net/rpc/server.go:384 +0x14e
2018-06-19T09:07:10.015-0400 [DEBUG] plugin.terraform-provider-ibm: created by net/rpc.(*Server).ServeCodec
2018-06-19T09:07:10.015-0400 [DEBUG] plugin.terraform-provider-ibm: 	/usr/local/Cellar/go/1.10/libexec/src/net/rpc/server.go:480 +0x43a
2018/06/19 09:07:10 [TRACE] root: eval: *terraform.EvalWriteState
2018/06/19 09:07:10 [TRACE] root: eval: *terraform.EvalWriteState
2018/06/19 09:07:10 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2018/06/19 09:07:10 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2018/06/19 09:07:10 [TRACE] root: eval: *terraform.EvalWriteState
2018/06/19 09:07:10 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2018/06/19 09:07:10 [TRACE] root: eval: *terraform.EvalIf
2018/06/19 09:07:10 [TRACE] root: eval: *terraform.EvalIf
2018/06/19 09:07:10 [TRACE] root: eval: *terraform.EvalWriteState
2018/06/19 09:07:10 [TRACE] root: eval: *terraform.EvalWriteState
2018/06/19 09:07:10 [TRACE] root: eval: *terraform.EvalWriteDiff
2018/06/19 09:07:10 [TRACE] root: eval: *terraform.EvalApplyPost
2018-06-19T09:07:10.018-0400 [DEBUG] plugin: plugin process exited: path=/opt/provider/terraform-provider-ibm
2018/06/19 09:07:10 [TRACE] root: eval: *terraform.EvalWriteDiff
2018/06/19 09:07:10 [TRACE] root: eval: *terraform.EvalApplyPost
2018/06/19 09:07:10 [TRACE] root: eval: *terraform.EvalIf
2018/06/19 09:07:10 [TRACE] root: eval: *terraform.EvalWriteState
2018/06/19 09:07:10 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* ibm_lbaas.master-lbaas-int: unexpected EOF
2018/06/19 09:07:10 [TRACE] root: eval: *terraform.EvalWriteDiff
2018/06/19 09:07:10 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* ibm_lbaas.master-lbaas-int: unexpected EOF
2018/06/19 09:07:10 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* ibm_lbaas.proxy-lbaas: unexpected EOF
2018/06/19 09:07:10 [TRACE] [walkApply] Exiting eval tree: ibm_lbaas.master-lbaas-int
2018/06/19 09:07:10 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* ibm_lbaas.proxy-lbaas: unexpected EOF
2018/06/19 09:07:10 [TRACE] [walkApply] Exiting eval tree: ibm_lbaas.proxy-lbaas
2018/06/19 09:07:10 [TRACE] root: eval: *terraform.EvalApplyPost
2018/06/19 09:07:10 [TRACE] dag/walk: upstream errored, not walking "local.proxy_addr"
2018/06/19 09:07:10 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* ibm_lbaas.master-lbaas: unexpected EOF
2018/06/19 09:07:10 [TRACE] dag/walk: upstream errored, not walking "local.console_addr_int"
2018/06/19 09:07:10 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* ibm_lbaas.master-lbaas: unexpected EOF
2018/06/19 09:07:10 [TRACE] dag/walk: upstream errored, not walking "output.ICP Proxy load balancer DNS (external)"
2018/06/19 09:07:10 [TRACE] [walkApply] Exiting eval tree: ibm_lbaas.master-lbaas
2018/06/19 09:07:10 [TRACE] dag/walk: upstream errored, not walking "ibm_lbaas_server_instance_attachment.icp_proxy[2]"
2018/06/19 09:07:10 [TRACE] dag/walk: upstream errored, not walking "ibm_lbaas_server_instance_attachment.icp-master-int[1]"
2018/06/19 09:07:10 [TRACE] dag/walk: upstream errored, not walking "output.ICP Console load balancer DNS (internal)"
2018/06/19 09:07:10 [TRACE] dag/walk: upstream errored, not walking "ibm_lbaas_server_instance_attachment.icp-master-int[2]"
2018/06/19 09:07:10 [TRACE] dag/walk: upstream errored, not walking "ibm_lbaas_server_instance_attachment.icp-master-int[0]"
2018/06/19 09:07:10 [TRACE] dag/walk: upstream errored, not walking "local.console_addr"
2018/06/19 09:07:10 [TRACE] dag/walk: upstream errored, not walking "ibm_lbaas_server_instance_attachment.icp_master[1]"
2018/06/19 09:07:10 [TRACE] dag/walk: upstream errored, not walking "ibm_lbaas_server_instance_attachment.icp_master[0]"
2018/06/19 09:07:10 [TRACE] dag/walk: upstream errored, not walking "ibm_lbaas_server_instance_attachment.icp_proxy[0]"
2018/06/19 09:07:10 [TRACE] dag/walk: upstream errored, not walking "ibm_lbaas_server_instance_attachment.icp_master[2]"
2018/06/19 09:07:10 [TRACE] dag/walk: upstream errored, not walking "output.ICP Kubernetes API URL"
2018/06/19 09:07:10 [TRACE] dag/walk: upstream errored, not walking "output.ICP Console URL"
2018/06/19 09:07:10 [TRACE] dag/walk: upstream errored, not walking "ibm_lbaas_server_instance_attachment.icp_proxy[1]"
2018/06/19 09:07:10 [TRACE] dag/walk: upstream errored, not walking "output.ICP Registry URL"
2018/06/19 09:07:10 [TRACE] dag/walk: upstream errored, not walking "module.icpprovision.var.icp_configuration"
2018/06/19 09:07:10 [TRACE] dag/walk: upstream errored, not walking "provider.ibm (close)"
2018/06/19 09:07:10 [TRACE] dag/walk: upstream errored, not walking "output.ICP Console load balancer DNS (external)"
2018/06/19 09:07:10 [TRACE] dag/walk: upstream errored, not walking "module.icpprovision.null_resource.icp-boot"
2018/06/19 09:07:10 [TRACE] dag/walk: upstream errored, not walking "module.icpprovision.null_resource.icp-config"
2018/06/19 09:07:10 [TRACE] dag/walk: upstream errored, not walking "module.icpprovision.null_resource.icp-generate-hosts-files"
2018/06/19 09:07:10 [TRACE] dag/walk: upstream errored, not walking "module.icpprovision.null_resource.icp-install"
2018/06/19 09:07:10 [TRACE] dag/walk: upstream errored, not walking "module.icpprovision.null_resource.icp-worker-scaler"
2018/06/19 09:07:10 [TRACE] dag/walk: upstream errored, not walking "provider.null (close)"
2018/06/19 09:07:10 [TRACE] dag/walk: upstream errored, not walking "module.icpprovision.output.install_complete"
2018/06/19 09:07:10 [TRACE] dag/walk: upstream errored, not walking "provisioner.remote-exec (close)"
2018/06/19 09:07:10 [TRACE] dag/walk: upstream errored, not walking "provisioner.file (close)"
2018/06/19 09:07:10 [TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2018/06/19 09:07:10 [TRACE] dag/walk: upstream errored, not walking "root"
2018/06/19 09:07:10 [TRACE] Preserving existing state lineage "d6d7f035-b023-8f52-1c13-75c81e088a05"
2018/06/19 09:07:10 [TRACE] Preserving existing state lineage "d6d7f035-b023-8f52-1c13-75c81e088a05"
2018/06/19 09:07:10 [TRACE] Preserving existing state lineage "d6d7f035-b023-8f52-1c13-75c81e088a05"
2018/06/19 09:07:10 [TRACE] Preserving existing state lineage "d6d7f035-b023-8f52-1c13-75c81e088a05"
2018/06/19 09:07:10 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-06-19T09:07:10.052-0400 [WARN ] plugin: error closing client during Kill: err="connection is shut down"
2018-06-19T09:07:10.054-0400 [DEBUG] plugin.terraform: local-exec-provisioner (internal) 2018/06/19 09:07:10 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-06-19T09:07:10.054-0400 [DEBUG] plugin.terraform: remote-exec-provisioner (internal) 2018/06/19 09:07:10 [ERR] plugin: plugin server: accept unix /var/folders/96/7_7_s99n5x36c8yzmldllp5c0000gn/T/plugin071536119: use of closed network connection
2018-06-19T09:07:10.054-0400 [DEBUG] plugin.terraform: remote-exec-provisioner (internal) 2018/06/19 09:07:10 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-06-19T09:07:10.054-0400 [DEBUG] plugin.terraform: file-provisioner (internal) 2018/06/19 09:07:10 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-06-19T09:07:10.057-0400 [DEBUG] plugin: plugin process exited: path=/Users/jkwong/git/terraform-icp-ibmcloud/.terraform/plugins/darwin_amd64/terraform-provider-random_v1.2.0_x4
2018-06-19T09:07:10.057-0400 [DEBUG] plugin: plugin process exited: path=/Users/jkwong/git/terraform-icp-ibmcloud/.terraform/plugins/darwin_amd64/terraform-provider-null_v1.0.0_x4
2018-06-19T09:07:10.057-0400 [DEBUG] plugin: plugin process exited: path=/Users/jkwong/git/terraform-icp-ibmcloud/.terraform/plugins/darwin_amd64/terraform-provider-tls_v1.1.0_x4
2018-06-19T09:07:10.059-0400 [DEBUG] plugin: plugin process exited: path=/usr/local/Cellar/terraform/0.11.7/bin/terraform
2018-06-19T09:07:10.059-0400 [DEBUG] plugin: plugin process exited: path=/usr/local/Cellar/terraform/0.11.7/bin/terraform
2018-06-19T09:07:10.059-0400 [DEBUG] plugin: plugin process exited: path=/usr/local/Cellar/terraform/0.11.7/bin/terraform



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by Praveengostu** [comment]
@jkwong888  looking in to it

**Comment by Praveengostu** [comment]
The issue occurs with protocol "tcp" and this is fine with other protocols.. We are working on the fix and will update once it is available
