### ISSUE TITLE
Terraform-provider-ibm_v1.29.0 plugin crashed!

### ISSUE THREAD

**Issue by pmgl0935** [IBM-Cloud/terraform-provider-ibm#2918]
Running Terraform v0.15.5 with terraform-provider-ibm_v1.29.0 pluging.
No change in HCL code. Just run a terraform plan and got this:

```
null_resource.deploy_maximo_dev: Refreshing state... [id=6996677992779624238]
╷
│ Error: Plugin did not respond
│ 
│   with module.dns.ibm_dns_zone.dns_zone,
│   on modules/shared-services/dns/main.tf line 13, in resource "ibm_dns_zone" "dns_zone":
│   13: resource "ibm_dns_zone" "dns_zone" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-ibm_v1.29.0 plugin:

panic: Invalid diagnostic: empty summary. This is always a bug in the provider implementation

goroutine 344 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/internal/plugin/convert.DiagsToProto(0xc001289400, 0x1, 0x1, 0xc000bdb500, 0x18, 0x18)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/internal/plugin/convert/diagnostics.go:72 +0x35c
github.com/hashicorp/terraform-plugin-sdk/v2/internal/plugin/convert.AppendProtoDiag(0x0, 0x0, 0x0, 0x23f3160, 0xc000bdb500, 0xc0015f8000, 0xc00033c770, 0xc001289400)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/internal/plugin/convert/diagnostics.go:25 +0x99
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00042f710, 0x2c9ba48, 0xc0000af680, 0xc0000af6c0, 0xc0000af680, 0x40ba05, 0x2636560)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/grpc_provider.go:576 +0x4b9
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc000b692a0, 0x2c9baf0, 0xc0000af680, 0xc000a374a0, 0xc000b692a0, 0xc000a519e0, 0xc0009c1ba0)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x26dd080, 0xc000b692a0, 0x2c9baf0, 0xc000a519e0, 0xc000a37440, 0x0, 0x2c9baf0, 0xc000a519e0, 0xc000b78d80, 0x20e)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000b96000, 0x2cb47b8, 0xc000403c80, 0xc0012c8b00, 0xc000674960, 0x39dd430, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000b96000, 0x2cb47b8, 0xc000403c80, 0xc0012c8b00, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00049a500, 0xc000b96000, 0x2cb47b8, 0xc000403c80, 0xc0012c8b00)
        google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-ibm_v1.29.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by kavya498** [comment]
Not able to reproduce this issue.. 
Kindly, reopen if you still see this issue..
Thanks..
