### ISSUE TITLE
Provider 1.30 crashes on ibm_kms_key when calling apply twice

### ISSUE THREAD

**Issue by l2fprod** [IBM-Cloud/terraform-provider-ibm#3011]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

```
Terraform v1.0.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/ibm-cloud/ibm v1.30.0
```

### Affected Resource(s)

* ibm_kms_key

### Panic Output

```
╷
│ Error: Plugin did not respond
│
│   with ibm_kms_key.key,
│   on main.tf line 79, in resource "ibm_kms_key" "key":
│   79: resource "ibm_kms_key" "key" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵

Stack trace from the terraform-provider-ibm_v1.30.0 plugin:

panic: interface conversion: error is *kp.URLError, not *kp.Error

goroutine 112 [running]:
github.com/IBM-Cloud/terraform-provider-ibm/ibm.resourceIBMKmsKeyExists(0xc000fafc00, 0x28aace0, 0xc000dca000, 0x0, 0x0, 0x1)
	github.com/IBM-Cloud/terraform-provider-ibm/ibm/resource_ibm_kms_key.go:690 +0x89a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000872540, 0x2db47c8, 0xc0002bd400, 0xc000331110, 0x28aace0, 0xc000dca000, 0xc000fb67c0, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:604 +0x3d5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00000cab0, 0x2db47c8, 0xc0002bd400, 0xc0002bd440, 0xc0002bd400, 0x40ba05, 0x272fc40)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc000dfcb00, 0x2db4870, 0xc0002bd400, 0xc00035aa80, 0xc000dfcb00, 0xc0008bd2f0, 0xc000e3aba0)
	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x27d9280, 0xc000dfcb00, 0x2db4870, 0xc0008bd2f0, 0xc00035aa20, 0x0, 0x2db4870, 0xc0008bd2f0, 0xc00070a900, 0x44a)
	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00009b880, 0x2dcd3d8, 0xc000001380, 0xc000bb3c00, 0xc000a829c0, 0x3b49510, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00009b880, 0x2dcd3d8, 0xc000001380, 0xc000bb3c00, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0004096c0, 0xc00009b880, 0x2dcd3d8, 0xc000001380, 0xc000bb3c00)
	google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-ibm_v1.30.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Steps to Reproduce

I ran `terraform apply` twice, and I'm also using IBMCLOUD_VISIBILITY=private

1. Use the template in https://github.com/IBM-Cloud/terraform-provider-ibm/issues/2929
2. `terraform init`
3. `terraform apply`
4. `terraform apply`
5. CRASH

**Comment by harshit777** [comment]
Hi! @l2fprod, There seems to be a bug and we are working on it. Until its not urgent and not causing any blockers, it will be resolved with the next terraform ibm provider release.

Thanks

**Comment by harshit777** [comment]
As a workaround to the current scenario, we would encourage you to use `endpoint_type` as `private` in resource block in your tf file while provsioning kms_key or any kms resource.

**Comment by harshit777** [comment]
@l2fprod Can you please check and confirm, so we can close this issue !

**Comment by kavya498** [comment]
Closing this issue due to inactivity.
Kindly, open new issue and tag this issue for reference..

Thank you..
