### ISSUE TITLE
ibm_dns_zones - invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by argeiger** [IBM-Cloud/terraform-provider-ibm#3142]
### Terraform CLI and Terraform IBM Provider Version

Terraform v0.14.7
+ provider registry.terraform.io/ibm-cloud/ibm v1.32.1

### Affected Resource(s)

* ibm_dns_zones

### Terraform Configuration Files

```hcl
data "ibm_dns_zones" "dns_zones" {
  instance_id = "<INSTANCE ID>"
}
```

### Debug Output / Panic Output

```
panic: runtime error: invalid memory address or nil pointer dereference
2021-09-23T17:33:36.482-0400 [DEBUG] plugin.terraform-provider-ibm_v1.32.1: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x290449f]
2021-09-23T17:33:36.482-0400 [DEBUG] plugin.terraform-provider-ibm_v1.32.1: 
2021-09-23T17:33:36.482-0400 [DEBUG] plugin.terraform-provider-ibm_v1.32.1: goroutine 93 [running]:
2021-09-23T17:33:36.482-0400 [DEBUG] plugin.terraform-provider-ibm_v1.32.1: github.com/IBM-Cloud/terraform-provider-ibm/ibm.dataSourceIBMPrivateDNSZonesRead(0xc001076580, 0x3575da0, 0xc001586000, 0x48d7b80, 0xc000176900)
2021-09-23T17:33:36.482-0400 [DEBUG] plugin.terraform-provider-ibm_v1.32.1: 	github.com/IBM-Cloud/terraform-provider-ibm/ibm/data_source_ibm_private_dns_zones.go:92 +0x1bf
2021-09-23T17:33:36.482-0400 [DEBUG] plugin.terraform-provider-ibm_v1.32.1: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000c1b340, 0x3a98228, 0xc0014ce380, 0xc001076580, 0x3575da0, 0xc001586000, 0x0, 0x0, 0x0)
2021-09-23T17:33:36.482-0400 [DEBUG] plugin.terraform-provider-ibm_v1.32.1: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:335 +0x1ee
2021-09-23T17:33:36.482-0400 [DEBUG] plugin.terraform-provider-ibm_v1.32.1: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc000c1b340, 0x3a98228, 0xc0014ce380, 0xc00043ab40, 0x3575da0, 0xc001586000, 0xc001586000, 0xc00043ab40, 0x0, 0x0)
2021-09-23T17:33:36.482-0400 [DEBUG] plugin.terraform-provider-ibm_v1.32.1: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:558 +0xfd
2021-09-23T17:33:36.483-0400 [DEBUG] plugin.terraform-provider-ibm_v1.32.1: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc000126630, 0x3a98228, 0xc0014ce380, 0xc00043aa80, 0xc0014ce380, 0x100b705, 0x33f7000)
2021-09-23T17:33:36.483-0400 [DEBUG] plugin.terraform-provider-ibm_v1.32.1: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/grpc_provider.go:1105 +0x4d6
2021-09-23T17:33:36.483-0400 [DEBUG] plugin.terraform-provider-ibm_v1.32.1: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadDataSource(0xc000f09a40, 0x3a982d0, 0xc0014ce380, 0xc0015a25f0, 0xc000f09a40, 0xc000a0c270, 0xc001597ba0)
2021-09-23T17:33:36.483-0400 [DEBUG] plugin.terraform-provider-ibm_v1.32.1: 	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:247 +0xe5
2021-09-23T17:33:36.483-0400 [DEBUG] plugin.terraform-provider-ibm_v1.32.1: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler(0x34a2080, 0xc000f09a40, 0x3a982d0, 0xc000a0c270, 0xc0014e0360, 0x0, 0x3a982d0, 0xc000a0c270, 0xc0014d42a0, 0x5a)
2021-09-23T17:33:36.483-0400 [DEBUG] plugin.terraform-provider-ibm_v1.32.1: 	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:416 +0x214
2021-09-23T17:33:36.483-0400 [DEBUG] plugin.terraform-provider-ibm_v1.32.1: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000168380, 0x3ab1358, 0xc000582600, 0xc00149cd00, 0xc000d5f4a0, 0x48798b0, 0x0, 0x0, 0x0)
2021-09-23T17:33:36.483-0400 [DEBUG] plugin.terraform-provider-ibm_v1.32.1: 	google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
2021-09-23T17:33:36.483-0400 [DEBUG] plugin.terraform-provider-ibm_v1.32.1: google.golang.org/grpc.(*Server).handleStream(0xc000168380, 0x3ab1358, 0xc000582600, 0xc00149cd00, 0x0)
2021-09-23T17:33:36.483-0400 [DEBUG] plugin.terraform-provider-ibm_v1.32.1: 	google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
2021-09-23T17:33:36.483-0400 [DEBUG] plugin.terraform-provider-ibm_v1.32.1: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000136240, 0xc000168380, 0x3ab1358, 0xc000582600, 0xc00149cd00)
2021-09-23T17:33:36.483-0400 [DEBUG] plugin.terraform-provider-ibm_v1.32.1: 	google.golang.org/grpc@v1.32.0/server.go:859 +0xab
2021-09-23T17:33:36.483-0400 [DEBUG] plugin.terraform-provider-ibm_v1.32.1: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-09-23T17:33:36.483-0400 [DEBUG] plugin.terraform-provider-ibm_v1.32.1: 	google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
```

**Comment by DanielFarrarCO** [comment]
I am also receiving this error, in my case I am using the Ansible module which calls this backend TF.

**Comment by kavya498** [comment]
Hi,
Crash should not have happened.. that ll be fixed from provider end.. 
But for some reason SDK returns nil as response.. It has to be fixed from SDK..
@shivaleelac , @MalarvizhiK FYI

**Comment by shivaleelac** [comment]
@kavya498 working with API team to fix this SDK returns nil

**Comment by hkantare** [comment]
closing this since we have fix from API side
