### ISSUE TITLE
TimeoutException when 

### ISSUE THREAD

**Issue by mrlockstar** [IBM-Cloud/terraform-provider-ibm#3571]
Possible issue, it looks like there is a limited number of concurrent connections you can have on the cluster at any one time: -

```
16:58:59.934 [main] ERROR - Failed to run the workload '1 producer / 1 consumers on 1 topic' for driver 'driver-pulsar/pulsar-effectively-once.yaml'
java.io.IOException: org.apache.pulsar.client.admin.PulsarAdminException$TimeoutException: java.util.concurrent.TimeoutException
   at io.openmessaging.benchmark.driver.pulsar.PulsarBenchmarkDriver.initialize(PulsarBenchmarkDriver.java:162) ~[driver-pulsar-0.0.1-SNAPSHOT.jar:?]
   at io.openmessaging.benchmark.worker.LocalWorker.initializeDriver(LocalWorker.java:134) ~[classes/:?]
   at io.openmessaging.benchmark.Benchmark.lambda$main$0(Benchmark.java:153) ~[classes/:?]
   at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_311]
   at io.openmessaging.benchmark.Benchmark.lambda$main$1(Benchmark.java:142) ~[classes/:?]
   at java.util.TreeMap.forEach(TreeMap.java:1005) [?:1.8.0_311]
   at io.openmessaging.benchmark.Benchmark.main(Benchmark.java:141) [classes/:?]Caused by: org.apache.pulsar.client.admin.PulsarAdminException$TimeoutException: java.util.concurrent.TimeoutException
   at org.apache.pulsar.client.admin.internal.TenantsImpl.getTenants(TenantsImpl.java:56) ~[pulsar-client-all-2.9.1.jar:2.9.1]
   at io.openmessaging.benchmark.driver.pulsar.PulsarBenchmarkDriver.initialize(PulsarBenchmarkDriver.java:133) ~[driver-pulsar-0.0.1-SNAPSHOT.jar:?]
   ... 6 more
Caused by: java.util.concurrent.TimeoutException
   at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1784) ~[?:1.8.0_311]
   at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928) ~[?:1.8.0_311]
   at org.apache.pulsar.client.admin.internal.TenantsImpl.getTenants(TenantsImpl.java:49) ~[pulsar-client-all-2.9.1.jar:2.9.1]
   at io.openmessaging.benchmark.driver.pulsar.PulsarBenchmarkDriver.initialize(PulsarBenchmarkDriver.java:133) ~[driver-pulsar-0.0.1-SNAPSHOT.jar:?]
   ... 6 more
16:59:00.103 [main] INFO - Shutting down Pulsar benchmark driver
```

This occurs when the using the open message load testing software when running the workloads/1-topic-16-partitions-1kb.yaml on four different ec2 nodes at the same time. It's worth noting that when a single instance of this is fired at the cluster it is able to handle without falling over. 

**To repeat**

1) build a cluster or use an existing cluster
2) clone repo pulsar-open-message-benchmark
3) Switch to branch origin/feat/takePartsForPulsar
4) Modify the terraform.tfvars file and put in the correct serviceUrl and httpUrl for the target cluster
5) deploy terraform  from with the terraform directory

**Comment by kavya498** [comment]
Can we get link to your repository? and complete terraform logs?

**Comment by mrlockstar** [comment]
This is been put into the incorrect repo by mistake. I will therefore close this issue.
