### ISSUE TITLE
Terrafrom crashes with ibm_resource_key

### ISSUE THREAD

**Issue by minsikl** [IBM-Cloud/terraform-provider-ibm#451]
### Terraform Version
Terraform v0.11.10
IBM Cloud Provider version 0.13.0

### Affected Resource(s)
- ibm_resource_key

### Terraform Configuration Files
```hcl
resource "ibm_resource_key" "cloudant-key" {
  name                 = "cloudant-key"
  role                 = "Manager"
  resource_instance_id = "Cloudantdb instance id"
}
```

### Debug Output
```
panic: interface conversion: interface {} is nil, not string
2018-12-10T23:49:42.754-0500 [DEBUG] plugin.terraform-provider-ibm:
2018-12-10T23:49:42.754-0500 [DEBUG] plugin.terraform-provider-ibm: goroutine 153 [running]:
2018-12-10T23:49:42.754-0500 [DEBUG] plugin.terraform-provider-ibm: github.com/IBM-Cloud/terraform-provider-ibm/ibm.resourceIBMResourceKeyRead(0xc00026b2d0, 0x1f32840, 0xc000377380, 0xc00044e900, 0x3)
2018-12-10T23:49:42.754-0500 [DEBUG] plugin.terraform-provider-ibm: 	/go/src/github.com/IBM-Cloud/terraform-provider-ibm/ibm/resource_ibm_resource_key.go:181 +0x547
2018-12-10T23:49:42.754-0500 [DEBUG] plugin.terraform-provider-ibm: github.com/IBM-Cloud/terraform-provider-ibm/ibm.resourceIBMResourceKeyCreate(0xc00026b2d0, 0x1f32840, 0xc000377380, 0xc00026b2d0, 0x0)
2018-12-10T23:49:42.754-0500 [DEBUG] plugin.terraform-provider-ibm: 	/go/src/github.com/IBM-Cloud/terraform-provider-ibm/ibm/resource_ibm_resource_key.go:160 +0x9e4
2018-12-10T23:49:42.755-0500 [DEBUG] plugin.terraform-provider-ibm: github.com/IBM-Cloud/terraform-provider-ibm/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc00026a7e0, 0xc0002820f0, 0xc00028c7a0, 0x1f32840, 0xc000377380, 0x100d901, 0xc00073db80, 0x10ba57c)
2018-12-10T23:49:42.755-0500 [DEBUG] plugin.terraform-provider-ibm: 	/go/src/github.com/IBM-Cloud/terraform-provider-ibm/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:227 +0x351
2018-12-10T23:49:42.755-0500 [DEBUG] plugin.terraform-provider-ibm: github.com/IBM-Cloud/terraform-provider-ibm/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc00026ae00, 0xc0002820a0, 0xc0002820f0, 0xc00028c7a0, 0xc000374400, 0x18, 0x2fa2d80)
2018-12-10T23:49:42.755-0500 [DEBUG] plugin.terraform-provider-ibm: 	/go/src/github.com/IBM-Cloud/terraform-provider-ibm/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:283 +0x9c
2018-12-10T23:49:42.755-0500 [DEBUG] plugin.terraform-provider-ibm: github.com/IBM-Cloud/terraform-provider-ibm/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc0004bc4e0, 0xc00028c260, 0xc00052b030, 0x0, 0x0)
2018-12-10T23:49:42.755-0500 [DEBUG] plugin.terraform-provider-ibm: 	/go/src/github.com/IBM-Cloud/terraform-provider-ibm/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:527 +0x57
2018-12-10T23:49:42.755-0500 [DEBUG] plugin.terraform-provider-ibm: reflect.Value.call(0xc0003948a0, 0xc00052e010, 0x13, 0x1f57426, 0x4, 0xc00073df18, 0x3, 0x3, 0xc000044300, 0x0, ...)
2018-12-10T23:49:42.755-0500 [DEBUG] plugin.terraform-provider-ibm: 	/usr/local/go/src/reflect/value.go:447 +0x449
2018-12-10T23:49:42.755-0500 [DEBUG] plugin.terraform-provider-ibm: reflect.Value.Call(0xc0003948a0, 0xc00052e010, 0x13, 0xc00066b718, 0x3, 0x3, 0x0, 0x0, 0x0)
2018-12-10T23:49:42.755-0500 [DEBUG] plugin.terraform-provider-ibm: 	/usr/local/go/src/reflect/value.go:308 +0xa4
2018-12-10T23:49:42.755-0500 [DEBUG] plugin.terraform-provider-ibm: net/rpc.(*service).call(0xc0003929c0, 0xc0000bc190, 0xc000596020, 0xc000596040, 0xc000120000, 0xc00051a5a0, 0x1cba480, 0xc00028c260, 0x16, 0x1cba4c0, ...)
2018-12-10T23:49:42.755-0500 [DEBUG] plugin.terraform-provider-ibm: 	/usr/local/go/src/net/rpc/server.go:384 +0x14e
2018-12-10T23:49:42.755-0500 [DEBUG] plugin.terraform-provider-ibm: created by net/rpc.(*Server).ServeCodec
2018-12-10T23:49:42.755-0500 [DEBUG] plugin.terraform-provider-ibm: 	/usr/local/go/src/net/rpc/server.go:481 +0x47e
2018/12/10 23:49:42 [TRACE] root: eval: *terraform.EvalWriteState
2018/12/10 23:49:42 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2018/12/10 23:49:42 [TRACE] root: eval: *terraform.EvalIf
2018/12/10 23:49:42 [TRACE] root: eval: *terraform.EvalWriteState
2018/12/10 23:49:42 [TRACE] root: eval: *terraform.EvalWriteDiff
2018/12/10 23:49:42 [TRACE] root: eval: *terraform.EvalApplyPost
2018/12/10 23:49:42 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* ibm_resource_key.cloudant-key: unexpected EOF
2018/12/10 23:49:42 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* ibm_resource_key.cloudant-key: unexpected EOF
2018/12/10 23:49:42 [TRACE] [walkApply] Exiting eval tree: ibm_resource_key.cloudant-key
2018/12/10 23:49:42 [TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2018/12/10 23:49:42 [TRACE] dag/walk: upstream errored, not walking "provider.ibm (close)"
2018/12/10 23:49:42 [TRACE] dag/walk: upstream errored, not walking "root"
2018-12-10T23:49:42.759-0500 [DEBUG] plugin: plugin process exited: path=/go/bin/terraform-provider-ibm
2018/12/10 23:49:42 [TRACE] Preserving existing state lineage "a8119abf-e8a4-50da-5e66-91aebefc076e"
2018/12/10 23:49:42 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-12-10T23:49:42.764-0500 [WARN ] plugin: error closing client during Kill: err="connection is shut down"



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

### Steps to Reproduce
`terraform apply`

**Comment by hkantare** [comment]
closing the issue
