### ISSUE TITLE
The terraform-provider-ibm_v1.53.0 plugin crashed

### ISSUE THREAD

**Issue by lionelmace** [IBM-Cloud/terraform-provider-ibm#4551]
I upgraded my [terraform code](https://github.com/lionelmace/mytodo/tree/master/cloud/terraform) from `1.52.1` to `1.53.0` but the plugin crashed. I'm running in [Terraform Cloud](https://app.terraform.io). I rolled back to the version `1.52.1` and it works again.

Below is the error:

```
Stack trace from the terraform-provider-ibm_v1.53.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8a9770]

goroutine 158 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc001374c40, {0x4677b40, 0xc002427e90}, 0xd?, {0x3e3c620, 0xc002284a80})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:707 +0x110
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc001374c40, {0x4677b40, 0xc002427e90}, 0xc000e1b6c0, 0xc000ae5f00, {0x3e3c620, 0xc002284a80})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:837 +0xa7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00052a648, {0x4677b40?, 0xc0023de360?}, 0xc0016c2c30)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0006f6320, {0x4677b40?, 0xc002427950?}, 0xc002410af0)
github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x3ccd0e0?, 0xc0006f6320}, {0x4677b40, 0xc002427950}, 0xc002410a80, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000792780, {0x467e540, 0xc000bbbba0}, 0xc0017ba6c0, 0xc001397b00, 0x617d580, 0x0)
google.golang.org/grpc@v1.48.0/server.go:1295 +0xb0b
google.golang.org/grpc.(*Server).handleStream(0xc000792780, {0x467e540, 0xc000bbbba0}, 0xc0017ba6c0, 0x0)
google.golang.org/grpc@v1.48.0/server.go:1636 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-ibm_v1.53.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by lionelmace** [comment]
I ran it again and it works now. I do not reproduce any more.
