### ISSUE TITLE
Confusion between secrets-manager CA and DNS configs

### ISSUE THREAD

**Issue by shemau** [IBM-Cloud/terraform-provider-ibm#4665]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

Terraform v1.5.1
IBM Provider v1.54.0

### Affected Resource(s)

* ibm_sm_public_certificate_configuration_dns_cis
* ibm_sm_public_certificate_configuration_ca_lets_encrypt

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please share a link to the ZIP file.
```

### Expected Behavior

1. Provision CA and DNS configs, which are different resource types, with the same name.

2. When deleting the DNS config (outside of terraform), I expect the resource DNS to show to be recreated during the next apply

### Actual Behavior

1. Resources (both CA and DNS configs) were created and were visible in the secrets manager. But, the apply failed.

2. The provider just crashes on terraform plan.

Making a lot of assumptions, I would conclude that the terraform provider can not distinguish between CA and DNS configs. Thus when creating one of each, it detects a conflict.  This is then made worse, when terraform thinks they both exist (both in the state file) and it only finds a CA config which it tries to process as a DNS config and panics the provider.

1. The deploy failed with:

```hcl
    module.secrets_manager[0].ibm_resource_instance.secrets_manager_instance: Still creating... [8m10s elapsed]
    module.secrets_manager[0].ibm_resource_instance.secrets_manager_instance: Creation complete after 8m18s [id=crn:v1:bluemix:public:secrets-manager:us-east:a/abac0df06b644a9cabc6e44f55b3880e:3c963726-4d83-41fb-8840-506bc4b66e5c::]
    module.secrets_manager_secret_group.ibm_sm_secret_group.secret_group: Creating...
    module.secrets_manager_public_cert_engine[0].ibm_iam_authorization_policy.cis_service_authorization[0]: Creating...
    module.secrets_manager_secret_group.ibm_sm_secret_group.secret_group: Creation complete after 3s [id=us-east/3c963726-4d83-41fb-8840-506bc4b66e5c/754abf6c-cc0a-1587-90e9-09c7fa7ba791]
    module.secrets_manager_public_cert_engine[0].ibm_iam_authorization_policy.cis_service_authorization[0]: Creation complete after 7s [id=09d8a6e1-a307-4d1d-8191-009224edf64c]
    module.secrets_manager_public_cert_engine[0].ibm_sm_public_certificate_configuration_ca_lets_encrypt.public_ca_config[0]: Creating...
    module.secrets_manager_public_cert_engine[0].ibm_sm_public_certificate_configuration_dns_cis.public_dns_config[0]: Creating...
    ╷
    │ Error: GetConfigurationWithContext failed Multiple configurations matched the name: 'goldeneye'.Use the 'X-SM-Accept-Configuration-Type' header to resolve ambiguity. [secrets-manager.00060E]
    │ {
    │     "StatusCode": 300,
    │     "Headers": {
    │         "Cache-Control": [
    │             "no-store, no-cache, must-revalidate, proxy-revalidate,no-cache, max-age=0, no-store"
    │         ],
    │         "Cf-Cache-Status": [
    │             "DYNAMIC"
    │         ],
    │         "Cf-Ray": [
    │             "7e0e988d3f9a88b3-LHR"
    │         ],
    │         "Content-Security-Policy": [
    │             "default-src 'none'"
    │         ],
    │         "Content-Type": [
    │             "application/json; charset=utf-8"
    │         ],
    │         "Correlation-Id": [
    │             "92daf8c8-578c-89de-c3e9-74687e371ebe"
    │         ],
    │         "Date": [
    │             "Mon, 03 Jul 2023 10:55:24 GMT"
    │         ],
    │         "Expires": [
    │             "0"
    │         ],
    │         "Pragma": [
    │             "no-cache"
    │         ],
    │         "Server": [
    │             "cloudflare"
    │         ],
    │         "Strict-Transport-Security": [
    │             "max-age=31536000; includeSubDomains; preload"
    │         ],
    │         "Surrogate-Control": [
    │             "no-store"
    │         ],
    │         "Vary": [
    │             "Accept-Encoding"
    │         ],
    │         "X-Content-Type-Options": [
    │             "nosniff"
    │         ],
    │         "X-Envoy-Upstream-Service-Time": [
    │             "504"
    │         ]
    │     },
    │     "Result": {
    │         "errors": [
    │             {
    │                 "code": "multiple_choices",
    │                 "message": "Multiple configurations matched the name: 'goldeneye'.Use the 'X-SM-Accept-Configuration-Type' header to resolve ambiguity. [secrets-manager.00060E]",
    │                 "more_info": "https://cloud.ibm.com/apidocs/secrets-manager"
    │             }
    │         ],
    │         "status_code": 300,
    │         "trace": "92daf8c8-578c-89de-c3e9-74687e371ebe"
    │     },
    │     "RawResult": null
    │ }
    │ 
    │ 
    │   with module.secrets_manager_public_cert_engine[0].ibm_sm_public_certificate_configuration_dns_cis.public_dns_config[0],
    │   on .terraform/modules/secrets_manager_public_cert_engine/main.tf line 76, in resource "ibm_sm_public_certificate_configuration_dns_cis" "public_dns_config":
    │   76: resource "ibm_sm_public_certificate_configuration_dns_cis" "public_dns_config" {
    │ 
    ╵
    ╷
    │ Error: GetConfigurationWithContext failed Multiple configurations matched the name: 'goldeneye'.Use the 'X-SM-Accept-Configuration-Type' header to resolve ambiguity. [secrets-manager.00060E]
    │ {
    │     "StatusCode": 300,
    │     "Headers": {
    │         "Cache-Control": [
    │             "no-store, no-cache, must-revalidate, proxy-revalidate,no-cache, max-age=0, no-store"
    │         ],
    │         "Cf-Cache-Status": [
    │             "DYNAMIC"
    │         ],
    │         "Cf-Ray": [
    │             "7e0e988f7b3188b3-LHR"
    │         ],
    │         "Content-Security-Policy": [
    │             "default-src 'none'"
    │         ],
    │         "Content-Type": [
    │             "application/json; charset=utf-8"
    │         ],
    │         "Correlation-Id": [
    │             "f6cc3cb2-b7b4-eca4-7fd8-07628458dfc0"
    │         ],
    │         "Date": [
    │             "Mon, 03 Jul 2023 10:55:24 GMT"
    │         ],
    │         "Expires": [
    │             "0"
    │         ],
    │         "Pragma": [
    │             "no-cache"
    │         ],
    │         "Server": [
    │             "cloudflare"
    │         ],
    │         "Strict-Transport-Security": [
    │             "max-age=31536000; includeSubDomains; preload"
    │         ],
    │         "Surrogate-Control": [
    │             "no-store"
    │         ],
    │         "Vary": [
    │             "Accept-Encoding"
    │         ],
    │         "X-Content-Type-Options": [
    │             "nosniff"
    │         ],
    │         "X-Envoy-Upstream-Service-Time": [
    │             "237"
    │         ]
    │     },
    │     "Result": {
    │         "errors": [
    │             {
    │                 "code": "multiple_choices",
    │                 "message": "Multiple configurations matched the name: 'goldeneye'.Use the 'X-SM-Accept-Configuration-Type' header to resolve ambiguity. [secrets-manager.00060E]",
    │                 "more_info": "https://cloud.ibm.com/apidocs/secrets-manager"
    │             }
    │         ],
    │         "status_code": 300,
    │         "trace": "f6cc3cb2-b7b4-eca4-7fd8-07628458dfc0"
    │     },
    │     "RawResult": null
    │ }
    │ 
    │ 
    │   with module.secrets_manager_public_cert_engine[0].ibm_sm_public_certificate_configuration_ca_lets_encrypt.public_ca_config[0],
    │   on .terraform/modules/secrets_manager_public_cert_engine/main.tf line 87, in resource "ibm_sm_public_certificate_configuration_ca_lets_encrypt" "public_ca_config":
    │   87: resource "ibm_sm_public_certificate_configuration_ca_lets_encrypt" "public_ca_config" {
    │ 
    ╵
```

2. The deploy failed with: 

```hcl
    module.secrets_manager_public_cert_engine[0].ibm_sm_public_certificate_configuration_dns_cis.public_dns_config[0]: Refreshing state... [id=us-east/3c963726-4d83-41fb-8840-506bc4b66e5c/goldeneye]

    Planning failed. Terraform encountered an error while generating this plan.

    ╷
    │ Error: Plugin did not respond
    │
    │   with module.secrets_manager_public_cert_engine[0].ibm_sm_public_certificate_configuration_dns_cis.public_dns_config[0],
    │   on .terraform/modules/secrets_manager_public_cert_engine/main.tf line 76, in resource "ibm_sm_public_certificate_configuration_dns_cis" "public_dns_config":
    │   76: resource "ibm_sm_public_certificate_configuration_dns_cis" "public_dns_config" {
    │
    │ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
    ╵
    ╷
    │ Error: Plugin did not respond
    │
    │   with module.secrets_manager_public_cert_engine[0].ibm_sm_public_certificate_configuration_ca_lets_encrypt.public_ca_config[0],
    │   on .terraform/modules/secrets_manager_public_cert_engine/main.tf line 87, in resource "ibm_sm_public_certificate_configuration_ca_lets_encrypt" "public_ca_config":
    │   87: resource "ibm_sm_public_certificate_configuration_ca_lets_encrypt" "public_ca_config" {
    │
    │ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
    ╵

    Stack trace from the terraform-provider-ibm_v1.54.0 plugin:

    panic: interface conversion: secretsmanagerv2.ConfigurationIntf is *secretsmanagerv2.PublicCertificateConfigurationCALetsEncrypt, not *secretsmanagerv2.PublicCertificateConfigurationDNSCloudInternetServices

    goroutine 281 [running]:
    github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/secretsmanager.resourceIbmSmConfigurationPublicCertificateDNSCisRead({0x52e0ee8, 0xc0018c4f60}, 0xc000063c00, {0x4a9a140?, 0xc000b16a80})
        github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/secretsmanager/resource_ibm_sm_public_certificate_configuration_dns_cis.go:176 +0xfb4
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0014e6a80, {0x52e0f20, 0xc001a689c0}, 0xd?, {0x4a9a140, 0xc000b16a80})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:724 +0x12e
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0014e6a80, {0x52e0f20, 0xc001a689c0}, 0xc001b81a00, {0x4a9a140, 0xc000b16a80})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:1015 +0x585
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00059d3b0, {0x52e0f20?, 0xc001a688a0?}, 0xc001a6a140)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:613 +0x497
    github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0000270e0, {0x52e0f20?, 0xc001a682d0?}, 0xc0018c4d80)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:748 +0x49e
    github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x492a640?, 0xc0000270e0}, {0x52e0f20, 0xc001a682d0}, 0xc0000b0a10, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc00049c000, {0x52e79a0, 0xc00061c680}, 0xc001a56fc0, 0xc0015c8630, 0x6e0b910, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1295 +0xb0b
    google.golang.org/grpc.(*Server).handleStream(0xc00049c000, {0x52e79a0, 0xc00061c680}, 0xc001a56fc0, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1636 +0xa1b
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.48.0/server.go:932 +0x98
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

    Error: The terraform-provider-ibm_v1.54.0 plugin crashed!

    This is always indicative of a bug within the plugin. It would be immensely
    helpful if you could report the crash with the plugin's maintainers so that it
    can be fixed. The output above should help diagnose the issue.
```

### Steps to Reproduce

1. `terraform apply` to create an SM with both CA config and DNS config with the same name

2. manually remove DNS config and `terraform plan` to cause the second condition, the panic

### Important Factoids

Resources used during this failure have been destroyed and no longer valid. High entropy strings above have been accessed

### References

* #0000

**Comment by haimsch** [comment]
@shemau That is a limitation of the Secrets Manager API. Configurations need to have a unique name regardless of the type of configuration. You will get the same error if you try to create the configurations with the Secrets Manager UI , the CLI or Terraform.
