### ISSUE TITLE
Provider plug-in crashed when `generation` parameter is missing

### ISSUE THREAD

**Issue by Nadine2016** [IBM-Cloud/terraform-provider-ibm#619]
I wanted to create a VPC and VSI on classic. What I did not know was that I had to specify `generation = 1` in the `provider.tf` file. When I ran my `terraform plan` command, everything looked fine, but then after running `terraform apply`, I saw the following error message: 

```
Error: Error applying plan:
1 error occurred:
    * ibm_is_vpc.vpc: 1 error occurred:
    * ibm_is_vpc.vpc: unexpected EOF
Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
panic: runtime error: invalid memory address or nil pointer dereference
2019-06-27T11:37:10.970-0400 [DEBUG] plugin.terraform-provider-ibm_v0.17.1: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1d500f3]
2019-06-27T11:37:10.970-0400 [DEBUG] plugin.terraform-provider-ibm_v0.17.1: 
2019-06-27T11:37:10.970-0400 [DEBUG] plugin.terraform-provider-ibm_v0.17.1: goroutine 180 [running]:
2019-06-27T11:37:10.970-0400 [DEBUG] plugin.terraform-provider-ibm_v0.17.1: github.com/IBM-Cloud/terraform-provider-ibm/ibm.isErrorToString(0x24f0340, 0xc420198720, 0x3, 0x2028000)
2019-06-27T11:37:10.970-0400 [DEBUG] plugin.terraform-provider-ibm_v0.17.1:     /Users/hkantare/go/src/github.com/IBM-Cloud/terraform-provider-ibm/ibm/resource_ibm_is_vpc.go:294 +0x123
2019-06-27T11:37:10.971-0400 [DEBUG] plugin.terraform-provider-ibm_v0.17.1: github.com/IBM-Cloud/terraform-provider-ibm/ibm.resourceIBMISVPCCreate(0xc4201de460, 0x2321220, 0xc42055c900, 0xc4201de460, 0x0)
2019-06-27T11:37:10.971-0400 [DEBUG] plugin.terraform-provider-ibm_v0.17.1:     /Users/hkantare/go/src/github.com/IBM-Cloud/terraform-provider-ibm/ibm/resource_ibm_is_vpc.go:118 +0x5a7
2019-06-27T11:37:10.971-0400 [DEBUG] plugin.terraform-provider-ibm_v0.17.1: github.com/IBM-Cloud/terraform-provider-ibm/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc4202c88c0, 0xc4206da0a0, 0xc4208ba660, 0x2321220, 0xc42055c900, 0xc420516801, 0xc4209d7b88, 0x10b530c)
2019-06-27T11:37:10.971-0400 [DEBUG] plugin.terraform-provider-ibm_v0.17.1:     /Users/hkantare/go/src/github.com/IBM-Cloud/terraform-provider-ibm/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:227 +0x35a
2019-06-27T11:37:10.971-0400 [DEBUG] plugin.terraform-provider-ibm_v0.17.1: github.com/IBM-Cloud/terraform-provider-ibm/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc4202fe770, 0xc4206da050, 0xc4206da0a0, 0xc4208ba660, 0x18, 0x18, 0xc4208ba780)
2019-06-27T11:37:10.971-0400 [DEBUG] plugin.terraform-provider-ibm_v0.17.1:     /Users/hkantare/go/src/github.com/IBM-Cloud/terraform-provider-ibm/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:283 +0xa4
2019-06-27T11:37:10.971-0400 [DEBUG] plugin.terraform-provider-ibm_v0.17.1: github.com/IBM-Cloud/terraform-provider-ibm/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc42082cca0, 0xc4208ba200, 0xc4205f2920, 0x0, 0x0)
2019-06-27T11:37:10.971-0400 [DEBUG] plugin.terraform-provider-ibm_v0.17.1:     /Users/hkantare/go/src/github.com/IBM-Cloud/terraform-provider-ibm/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:527 +0x57
2019-06-27T11:37:10.971-0400 [DEBUG] plugin.terraform-provider-ibm_v0.17.1: reflect.Value.call(0xc420090360, 0xc42000c008, 0x13, 0x233d4b9, 0x4, 0xc4209d7f18, 0x3, 0x3, 0xc4204f66c0, 0x1081db8, ...)
2019-06-27T11:37:10.971-0400 [DEBUG] plugin.terraform-provider-ibm_v0.17.1:     /usr/local/go/src/reflect/value.go:447 +0x969
2019-06-27T11:37:10.971-0400 [DEBUG] plugin.terraform-provider-ibm_v0.17.1: reflect.Value.Call(0xc420090360, 0xc42000c008, 0x13, 0xc4201f6718, 0x3, 0x3, 0x30003, 0xc4201f679e, 0xc4201f6798)
2019-06-27T11:37:10.971-0400 [DEBUG] plugin.terraform-provider-ibm_v0.17.1:     /usr/local/go/src/reflect/value.go:308 +0xa4
2019-06-27T11:37:10.971-0400 [DEBUG] plugin.terraform-provider-ibm_v0.17.1: net/rpc.(*service).call(0xc42075e100, 0xc4209f21e0, 0xc4205fc038, 0xc4205fc050, 0xc4201b0080, 0xc420a9a600, 0x1fd6300, 0xc4208ba200, 0x16, 0x1fd6340, ...)
2019-06-27T11:37:10.971-0400 [DEBUG] plugin.terraform-provider-ibm_v0.17.1:     /usr/local/go/src/net/rpc/server.go:384 +0x14e
2019-06-27T11:37:10.971-0400 [DEBUG] plugin.terraform-provider-ibm_v0.17.1: created by net/rpc.(*Server).ServeCodec
2019-06-27T11:37:10.971-0400 [DEBUG] plugin.terraform-provider-ibm_v0.17.1:     /usr/local/go/src/net/rpc/server.go:480 +0x43a
2019/06/27 11:37:10 [TRACE] root: eval: *terraform.EvalWriteState
2019/06/27 11:37:10 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2019-06-27T11:37:10.975-0400 [DEBUG] plugin: plugin process exited: path=/Users/ibm/.terraform.d/plugins/terraform-provider-ibm_v0.17.1
2019/06/27 11:37:10 [TRACE] root: eval: *terraform.EvalIf
2019/06/27 11:37:10 [TRACE] root: eval: *terraform.EvalWriteState
2019/06/27 11:37:10 [TRACE] root: eval: *terraform.EvalWriteDiff
2019/06/27 11:37:10 [TRACE] root: eval: *terraform.EvalApplyPost
2019/06/27 11:37:10 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error occurred:
    * ibm_is_vpc.vpc: unexpected EOF
2019/06/27 11:37:10 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error occurred:
    * ibm_is_vpc.vpc: unexpected EOF
2019/06/27 11:37:10 [TRACE] [walkApply] Exiting eval tree: ibm_is_vpc.vpc
2019/06/27 11:37:10 [TRACE] dag/walk: upstream errored, not walking "ibm_is_subnet.subnet1"
2019/06/27 11:37:10 [TRACE] dag/walk: upstream errored, not walking "ibm_is_security_group.sg1"
2019/06/27 11:37:10 [TRACE] dag/walk: upstream errored, not walking "ibm_is_security_group_rule.ingress_ssh_all"
2019/06/27 11:37:10 [TRACE] dag/walk: upstream errored, not walking "ibm_is_instance.vsi1"
2019/06/27 11:37:10 [TRACE] dag/walk: upstream errored, not walking "ibm_is_floating_ip.fip1"
2019/06/27 11:37:10 [TRACE] dag/walk: upstream errored, not walking "output.sshcommand"
2019/06/27 11:37:10 [TRACE] dag/walk: upstream errored, not walking "provider.ibm (close)"
2019/06/27 11:37:10 [TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2019/06/27 11:37:10 [TRACE] dag/walk: upstream errored, not walking "root"
2019/06/27 11:37:10 [TRACE] Preserving existing state lineage "b07f55e5-29a0-1aa1-34ca-ef1088f3d222"
2019/06/27 11:37:10 [DEBUG] plugin: waiting for all plugin processes to complete...
2019-06-27T11:37:10.995-0400 [WARN ] plugin: error closing client during Kill: err="connection is shut down"
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.
When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.
[1]: https://github.com/hashicorp/terraform/issues
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

This is a pretty bad error message for a missing parameter. Could we add better error handling and messaging to this?

**Comment by hkantare** [comment]
Presently we don't have complete support for NextGen...The API is still in beta...so there may be changes and it may break.

We have support for VPC Classic,so generation needs to be set to 2

**Comment by Nadine2016** [comment]
@hkantare so I tried it with generation=2, but the provider plug-in failed to provision the resources. it works when I use generation=1. I am trying to provision VPC on Classic. Will it be changed to "2" in the future? Or will "2" stand for NextGen?

**Comment by hkantare** [comment]
Here 2 stands for NexGen...As of now our provider doesn't have support for NextGen since its in Beta.

**Comment by Nadine2016** [comment]
@hkantare so I think that fits to what I did as I initially set generation = 1. I think I was just concerned that you get the error message above when you don't specify a generation in the provider part of your config file. I was wondering if instead of the error message above, we could just say something like: Infrastructure ID not found. Specify 'generation = 1' to provision VPC on Classic infrastructure." ?

**Comment by hkantare** [comment]
With latest provider v0.17.2 we are not facing any crash..
